[package]
name = "pigeon-common"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
chrono = "0.4.38"
tokio = { version = "1.42.0", features = ["sync"] }
