[package]
name = "pigeon-fake-messages"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
lipsum = "0.9.1"
pigeon-common = { workspace = true }
rand = "0.8.5"
tokio = { version = "1.42.0", features = ["sync", "time"] }
uuid = { version = "1.11.0", features = ["v7"] }
